### ISSUE TITLE
[FEATURE] Send Alerts to specific channels based on test / folder pattern

### ISSUE THREAD

**Issue by fspinillo** [ryanrosello-og/playwright-slack-report#123]
**Is your feature request related to a problem? Please describe.**
Exploring Playwright as a solution for our needs, and one of the things we utilize is a [reporter](https://github.com/bahmutov/cypress-slack-notify) that lets us notify teams/channels based on their tests failing. 

**Describe the solution you'd like**
The ability to notify a specific channel if a specific test/folder/pattern fails. So if a test in `tests/auth/**.spec.ts` fails, then notify the channel `#auth-team`.

**Additional context**

**Comment by ryanrosello-og** [comment]
hmm, tricky.  Theres an existing config here:
https://github.com/ryanrosello-og/playwright-slack-report?tab=readme-ov-file#onfailurechannels

But its pretty basic, currently it only accepts a string of channels.

from what I understood, you want something like:

```
{
  ...
  onFailureChannels: [
    {
      channelName: "failed-auth-channel",
      pattern: "tests/auth/**.spec.ts",
    },
    {
      channelName: "generic-automation-failures",
      pattern: "*",
    },
  ],
  ...
};
```
@fspinillo ?

**Comment by solidometall** [comment]
hi guys!
I needed the same thing so I made a fork of the repo and implemented some functions for:
- send failures to different channels, filtering tests by a specific pattern
- configure a different report for failures report

I think my code was not very well organized, and some tests fail because they should be updated. That's why I didn't make a request to add changes to the ryanrosello repo.
Feel free to analyze the changes and incorporate them to the main repo.

any suggestions are welcome

>> [link to the forked repo](https://github.com/solidometall/playwright-slack-report)
