### ISSUE TITLE
[QUESTION] - Collect the results of tests running on sharding and send them to one message to slack

### ISSUE THREAD

**Issue by hasangurhan** [ryanrosello-og/playwright-slack-report#56]
I run the tests on 5 machines using the Shard feature, and as expected, the results are messaged 5 times. Is it possible to send the results running in separate shards to Slack as a single Slack message?

**Comment by ryanrosello-og** [comment]
hey @hasangurhan, currently this is not supported.  I would need to implement.
This is what I'm thinking of implementing.

1. You will need to merge your results using `merge-reports` as a json file and redirect output to json file

`npx playwright merge-reports --reporter json .\shard-results > merged.json`

2. Run the playwright slack reporter separately and passing in required stuff. e.g. SLACK_BOT_USER_OAUTH_TOKEN, config file, path to the merged.json file

`SLACK_BOT_USER_OAUTH_TOKEN=xoxb-28794905334...  npx playwright-slack-reporter --config <CONFIG_FILE_FOR_SLACK_REPORTER> --json-results merged.json`

So in total, you will need 2 additional steps in your CI

Please let me know if this feasible in your current environment so that I can start work on the cli for step 2 above.

**Comment by ryanrosello-og** [comment]
hey @chrisotto6 , yes it will need to be removed from `playwright.config.ts`, I will most likely introduce a new config for this e.g. `pw_slack_report.config.json` or something.

**Comment by ryanrosello-og** [comment]
howdy @andiberisha-e2x, I will be working on this shortly.  Currently waiting for Playwright v1.40 to drop since it has a feature that is blocking me.

https://github.com/microsoft/playwright/issues/27498 < this feature specifically

**Comment by ryanrosello-og** [comment]
Implemented in v1.1.54
